name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Set up .env file
        run: echo "TEST_MONGODB_URI=${{ env.TEST_MONGODB_URI }}" > ./server/.env

      - name: Run tests
        working-directory: ./server
        run: npm run test

      - name: Build server
        working-directory: ./server
        run: npm run build
  version_bump:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}