name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build Docker Image
        working-directory: ./client
        env:
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
        run: |
          docker build -t client-image .

      - name: Deploy to Fly.io
        working-directory: ./client
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_CLIENT_TOKEN }}
        run: |
          flyctl deploy --remote-only --image client-image
