name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and Deploy Docker Image
        working-directory: ./client
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_CLIENT_TOKEN }}
        run: |
          docker build \
            --build-arg VITE_CLIENT_ID=${{ secrets.CLIENT_ID }} \
            --build-arg VITE_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            -t client-image .
          flyctl deploy --remote-only --image client-image