name: Fly Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy  
        working-directory: ./client
        run: flyctl deploy --remote-only --build-arg VITE_CLIENT_ID=${{ secrets.CLIENT_ID }} VITE_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_CLIENT_TOKEN }}