name: Fly Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    concurrency: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dentarg/fly@v1
      - name: deploy
        working-directory: ./client
        with:
          build-args: "VITE_CLIENT_ID=${{ secrets.CLIENT_ID }} VITE_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}"
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}